name: zero_to_ai_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - scikit-learn
  - spacy
  - xgboost
  - gensim
  - transformers
  - sentence-transformers
  - seaborn
  - pandas
  - ucimlrepo
  - matplotlib
  - pmdarima
  - pytest
  - jupyter
  - ipykernel
  - pip
  - pip:
      - skforecast